import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav: {
      home: 'Home', about: 'About', testimonials: 'Testimonials', services: 'Our Service',
      team: 'Our Team', shop: 'Shop', arrivals: 'New Arrivals', track: 'Track Order', contact: 'Contact',
    },
    common: {
      search: 'Search shoes…', login: 'Login', signup: 'Sign Up', logout: 'Logout',
      dashboard: 'Dashboard', cart: 'Cart', viewAll: 'View all →', shopNow: 'Shop Now',
      addToCart: 'Add to Cart', view: 'View', outOfStock: 'Out of Stock', noSizes: 'No sizes',
      remove: 'Remove', continueShopping: 'Continue shopping', subtotal: 'Subtotal',
      deliveryFee: 'Delivery fee', total: 'Total', yourCart: 'Your Cart', size: 'Size',
      orders: 'Orders', profile: 'Profile', wishlist: 'Wishlist',
    },
    status: {
      PENDING: 'Pending', PROCESSING: 'Processing', SHIPPED: 'Shipped', DELIVERED: 'Delivered',
      COMPLETED: 'Completed', CANCELLED: 'Cancelled', PAID: 'Paid', FAILED: 'Failed',
    },
    hero: {
      badge: 'Quality Sport Shoes. Great Prices.',
      title: 'GSKY SPORT SHOES', subtitle: 'STEP INTO YOUR GAME.',
      shopNow: 'SHOP NOW →', whatsapp: 'WHATSAPP US', hot: 'Hot right now',
      styles: 'Styles', categories: 'Categories', quality: 'Quality',
    },
    footer: {
      tagline: 'Quality sport shoes and sneakers at great prices. Step into your game with Gsky.',
      whatsapp: 'WhatsApp Us', shop: 'Shop', company: 'Company', findUs: 'Find Us',
      allShoes: 'All Shoes', featured: 'Featured', newArrivals: 'New Arrivals', bestSellers: 'Best Sellers',
      track: 'Track Your Order', about: 'About Us', contact: 'Contact',
      rights: 'All rights reserved.', developedBy: 'Developed by',
    },
    home: {
      shopByCategory: 'Shop by Category', products: 'products',
      newArrivals: 'New Arrivals', newArrivalsSub: 'Fresh drops — the latest to hit our shelves',
      featuredCollection: 'Featured Collection', featuredSub: 'Hand-picked favourites',
      bestSellers: 'Best Sellers', bestSellersSub: 'Loved by our customers',
    },
    shop: {
      title: 'SHOP ALL SHOES', productsAvailable: '{{n}} products available',
      searchPh: 'Search shoes…', allCategories: 'All Categories', allSizes: 'All Sizes',
      sortNewest: 'Newest', sortPriceAsc: 'Price: Low to High', sortPriceDesc: 'Price: High to Low',
      sortBestSellers: 'Best Sellers', noShoesFound: 'No shoes found',
      noShoesDesc: 'Try a different search or filter.', clearFilters: 'Clear filters',
      loadMore: 'Load more products',
    },
    product: {
      newArrival: 'New Arrival', bestSeller: 'Best Seller', featured: 'Featured',
      home: 'Home', shop: 'Shop', selectSize: 'Select Size',
      inStock: '{{n}} in stock', outOfStock: 'This size is out of stock',
      sizeGuide: '📏 Size Guide (EU)', us: 'US', uk: 'UK', footCm: 'Foot (cm)',
      sizeGuideHelp: 'Measure your foot from heel to longest toe, then match the length. If between sizes, go a half-size up. WhatsApp us on 0675029833 for sizing help.',
      quantity: 'Quantity', addToCart: '🛒 ADD TO CART', buyNow: 'BUY NOW',
      whatsappProduct: 'WHATSAPP ABOUT THIS PRODUCT',
      customerReviews: 'Customer Reviews ({{n}})',
      noReviews: 'No reviews yet. Be the first to review this product!',
      writeReview: 'Write a Review', rating: 'Rating', yourComment: 'Your comment',
      commentPh: 'How are the shoes?', addPhoto: 'Add a photo (optional)',
      photoAttached: 'Photo attached', submitReview: 'Submit Review',
      loginToReview: 'Login to write a review for purchased products.',
      customerPhoto: 'Customer photo', pleaseSelectSize: 'Please select a size',
      pleaseLoginCart: 'Please login to add items to your cart', pleaseLoginCheckout: 'Please login to checkout',
      addedToCart: 'Product added to cart ✓', thanksReview: 'Thanks for your review!',
      productNotFound: 'Product not found',
    },
    cart: {
      title: 'YOUR CART', emptyTitle: 'Your cart is empty',
      emptyDesc: 'Browse our shop and add some fresh shoes.', remove: 'Remove',
      clearCart: 'Clear cart', orderSummary: 'Order Summary', subtotal: 'Subtotal',
      deliveryFee: 'Delivery fee', total: 'Total', checkout: 'Checkout →',
      continueShopping: 'Continue shopping', size: 'Size',
      itemRemoved: 'Item removed from cart',
    },
    checkout: {
      stepDelivery: 'Delivery', stepPayment: 'Payment', stepDone: 'Done',
      emptyTitle: 'Your cart is empty', emptyDesc: 'Add some shoes first, then check out.',
      deliveryDetails: 'Delivery Details', fullName: 'Full name', phoneNumber: 'Phone number',
      email: 'Email', city: 'City', deliveryLocation: 'Delivery location',
      selectLocation: 'Select your location', street: 'Street / Location',
      streetPh: 'e.g. DIT, building 4', deliveryNotes: 'Delivery notes (optional)',
      notesPh: 'Any instructions for delivery', continueToPayment: 'Continue to Payment →',
      orderSummary: 'Order Summary', deliveryLabel: 'Delivery ({{zone}})',
      yourLocation: 'Your location', discount: 'Discount ({{code}})', promoApplied: 'Promo {{code}} applied',
      remove: 'Remove', promoCode: 'Promo code', apply: 'Apply',
      minOrder: 'Minimum order for this code is {{amount}}', promoAppliedMsg: 'Promo {{code}} applied!',
      choosePayment: 'Choose Payment Method', orderLine: 'Order {{number}} · Total {{total}}',
      cardPayment: 'Card Payment', cardNote: 'Credit / Debit card',
      processingPayment: 'Processing your sandbox payment…', reference: 'Reference: {{ref}}',
      simulated: 'This is a simulated payment for testing. No real money is charged.',
      pay: 'Pay {{amount}}', paymentSuccess: 'Payment Successful!',
      orderPaid: 'Your order {{number}} has been paid. A confirmation email is on its way.',
      totalPaid: 'Total paid', payment: 'Payment', weContact: 'We\'ll contact you on {{phone}} for delivery.',
      viewOrder: 'View Order', continueShopping: 'Continue Shopping',
      paymentFailed: 'Payment failed. Please try again.', paymentProcessing: 'Payment is still processing. Check your order status shortly.',
    },
    login: {
      title: 'Welcome back 👟', subtitle: 'Login to your Gsky account.',
      accountCreated: 'Account created! Welcome email sent to {{email}}. Login below to continue.',
      email: 'Email', password: 'Password', login: 'Login',
      noAccount: 'No account?', createOne: 'Create one',
      welcomeBack: 'Welcome back, {{name}}!',
    },
    register: {
      title: 'Create your account 👟', subtitle: 'Join the Gsky VIP family.',
      fullName: 'Full name', namePh: 'Nia Joseph', email: 'Email', phoneNumber: 'Phone number',
      password: 'Password', passPh: 'At least 6 characters', confirmPassword: 'Confirm password',
      repeatPh: 'Repeat password', create: 'Create Account', haveAccount: 'Already have an account?',
      login: 'Login', accountCreated: 'Account created! Welcome email sent to {{email}}. Please login.',
    },
    profile: {
      title: 'MY PROFILE', memberSince: 'Member since {{date}}', fullName: 'Full name',
      phoneNumber: 'Phone number', emailCannotChange: 'Email (cannot be changed)',
      save: 'Save Changes', updated: 'Profile updated ✓',
    },
    orders: {
      title: 'MY ORDERS', noOrders: 'No orders yet',
      noOrdersDesc: 'When you place an order it will appear here.', shopNow: 'Shop Now',
    },
    orderDetail: {
      myOrders: '← My orders', placed: 'Placed {{date}}',
      notPaid: 'This order is not paid yet.', completePayment: 'Complete payment to have your shoes shipped.',
      payNow: 'Pay now (Sandbox)', processing: 'Processing…',
      delivered: '🎉 Your parcel has been delivered!',
      youConfirmed: '✓ You confirmed delivery on {{date}}. We\'ll mark it complete shortly.',
      received: 'Received your shoes? Confirm delivery to complete your order.',
      confirming: 'Confirming…', confirmDelivery: 'Confirm Delivery',
      items: 'Items', subtotal: 'Subtotal', deliveryFee: 'Delivery fee', total: 'Total',
      delivery: 'Delivery', notes: 'Notes: {{notes}}', payments: 'Payments',
      paymentSuccess: 'Payment successful!', deliveryConfirmed: 'Delivery confirmed. Thank you!',
      paymentProcessing: 'Payment still processing. Try again shortly.',
    },
    track: {
      title: 'Track Your Order',
      subtitle: 'Enter the billing email you used at checkout and your Order ID from the confirmation email.',
      billingEmail: 'Billing email', orderId: 'Order ID', track: 'TRACK',
      placed: '{{name}} · Placed {{date}}', deliveryAddress: 'Delivery Address',
      items: 'Items', deliveryFee: 'Delivery fee', total: 'Total', notes: 'Notes: {{notes}}',
      sizeQty: '(Size {{size}} × {{qty}})',
    },
    timeline: {
      placed: 'Order Placed', processing: 'Processing', assigned: 'Assigned to Driver',
      delivered: 'Delivered', completed: 'Completed', cancelled: 'This order was cancelled',
      cancelledDesc: 'Contact us on WhatsApp for help.',
      currentStage: '{{stage}} is the current stage. Next: {{next}}.',
      orderCompleted: '🎉 Order completed. Enjoy your shoes!',
      confirmedByClient: '✓ Delivery confirmed by client {{date}}',
    },
    productCard: {
      new: 'New', bestSeller: 'Best Seller', outOfStock: 'Out of Stock',
      sizes: 'Sizes: {{sizes}}', noSizes: 'No sizes', addToCart: 'Add to Cart', view: 'View',
      added: 'Product added to cart ✓', loginToAdd: 'Please login to add items to your cart',
      outOfStockMsg: 'Product is currently out of stock',
    },
    homeSections: {
      shopNow: 'Shop Now', chatWhatsapp: 'Chat on WhatsApp',
    },
    services: {
      label: 'Our Service', title: 'SERVICE YOU CAN COUNT ON',
      subtitle: 'From Dar es Salaam to anywhere in Tanzania — we make buying sport shoes simple.',
      s1t: 'Fast Delivery in Dar es Salaam',
      s1d: 'Same-day delivery across Dar es Salaam and fast nationwide shipping. Order on WhatsApp or online and we get your shoes to you quickly.',
      s2t: 'Quality Guarantee',
      s2d: 'Every pair is checked before it leaves our shop at DIT, Morogoro Road. If something is wrong, we replace or refund — no long stories.',
      s3t: 'WhatsApp Ordering',
      s3d: 'Prefer to chat? Send us a message on WhatsApp, tell us your size and model, and we handle the rest. Payment on delivery available.',
      s4t: 'Size Exchange',
      s4d: 'Wrong size? No problem. Exchange any unworn pair within days of purchase, or visit us at Morogoro Road to try before you buy.',
      shopNow: 'Shop Now', chatWhatsapp: 'Chat on WhatsApp',
    },
    team: {
      label: 'Our Team', title: 'THE PEOPLE BEHIND GSKY',
      subtitle: 'A small, passionate team helping Tanzania play in the right shoes.',
      m1r: 'Founder & Sales Lead',
      m1d: 'Founded Gsky Sport Shoes at DIT with one mission — quality football boots at honest prices.',
      m2r: 'Operations & Warehouse',
      m2d: 'Keeps every order checked, packed and out the door fast from our Morogoro Road base.',
      m3r: 'Customer Care',
      m3d: 'Your first point of contact on WhatsApp — quick answers, size help and order updates.',
      cta: 'Want to work with us or visit the shop?', ctaLink: 'Message the team →',
    },
    testimonials: {
      label: 'Testimonials', title: 'WHAT OUR CUSTOMERS SAY',
      r1: 'Football player, Kinondoni',
      q1: 'I bought the Gsky Predator FG for my Sunday league. The grip on the firm ground is unreal — scored twice on debut. Delivery to Kinondoni was same day!',
      r2: 'Running enthusiast, Mikocheni',
      q2: 'The Runner Pro is the comfiest shoe I have owned. Light, breathable and the price is way better than the big brands. Gsky is now my go-to shop.',
      r3: 'Coach, Chang’ombe',
      q3: 'I ordered 12 pairs of Matchday TF for my academy players. The team communicated everything on WhatsApp and the boots lasted a full season.',
      r4: 'Futsal player, Buguruni',
      q4: 'The Court Indoor shoe is perfect for our futsal league. Non-marking soles, great grip, and my teammates keep asking where I got them!',
      r5: 'Gym owner, Posta',
      q5: 'I stock Gsky Power Gym shoes for my members. Great quality, fair wholesale pricing and reliable restock. Highly recommend working with them.',
      r6: 'Customer, Mwenge',
      q6: 'Easy ordering on WhatsApp, quick delivery and they helped me exchange size with zero stress. Excellent service all round.',
    },
    newsletter: {
      title: 'JOIN THE GSKY VIP LIST', sub: 'Get new arrivals, special offers and exclusive Gsky updates.',
      name: 'Your name', email: 'Email address', phone: 'Phone number (optional)',
      size: 'Your shoe size (optional)', agree: 'I agree to receive marketing emails from Gsky Sport Shoes.',
      subscribe: 'Subscribe — Join the VIP List', needConsent: 'Please agree to receive marketing emails',
      welcome: 'Welcome to the Gsky VIP list! 👟',
      unsubTitle: 'Unsubscribe', unsubSub: 'Enter your email to stop receiving marketing emails.',
      unsubBtn: 'Unsubscribe', unsubDone: 'You\'re unsubscribed',
      unsubDoneSub: 'You won\'t receive marketing emails from Gsky Sport Shoes anymore.',
      unsubSeo: 'Unsubscribe — Gsky Sport Shoes',
    },
    contact: {
      title: 'CONTACT US', subtitle: 'We\'d love to hear from you.',
      visitStore: 'Visit Our Store', storeLine: 'Gsky Sport Shoes · DIT, Morogoro Road · Dar es Salaam',
      address: 'Address', whatsapp: 'WhatsApp', hours: 'Hours',
      hoursLine: 'Mon – Sat\n9:00 AM – 7:00 PM',
      sendMessage: 'Send us a message', reply: 'We reply to every message within one business day.',
      yourName: 'Your name', yourEmail: 'Your email', subject: 'Subject',
      subjectPh: 'Order question, sizing help, partnership…', message: 'Message', messagePh: 'How can we help?',
      send: 'Send Message', noteWhatsapp: 'Fastest way to reach us', noteEmail: 'For formal inquiries',
      noteInstagram: 'Follow our latest drops', noteTiktok: 'Behind the scenes', noteFacebook: 'Community updates',
    },
    about: {
      title: 'ABOUT GSKY SPORT SHOES', subtitle: 'Step into your game.',
      whoWeAre: 'Who we are',
      p1: 'Gsky Sport Shoes is a Dar es Salaam-based sports shoe and sneaker store located at DIT, Morogoro Road. We believe that great performance starts from the ground up — that\'s why we stock quality sport shoes for running, basketball, football, training and everyday wear at prices that make sense.',
      p2: 'Whether you\'re chasing a personal best, dominating the court, or just want a clean pair of sneakers for the streets — Gsky has you covered. Browse our shop online, or reach us on WhatsApp and we\'ll help you find your perfect fit.',
      standFor: 'What we stand for',
      v1t: 'Quality First', v1d: 'Every pair we sell is chosen for durability, comfort and performance.',
      v2t: 'Great Prices', v2d: 'Real value for your money — quality sport shoes without the inflated markup.',
      v3t: 'Personal Service', v3d: 'Message us on WhatsApp any time. We help you pick the right fit.',
      v4t: 'Fast Delivery', v4d: 'Quick delivery across Dar es Salaam with careful packaging.',
      ready: 'Ready to step into your game?', shopNow: 'SHOP NOW', whatsappUs: 'WhatsApp Us',
    },
    wishlist: {
      title: 'MY WISHLIST', sub: 'Shoes you saved for later.',
      emptyTitle: 'Your wishlist is empty', emptyDesc: 'Tap the heart on any shoe to save it here.',
    },
    notFound: {
      title: 'Page not found', subtitle: 'The page you\'re looking for doesn\'t exist.',
      backHome: 'Back to Home',
    },
    error: {
      title: 'Something went wrong', retry: 'Try Again', home: 'Go Home',
      defaultSeo: 'GSKY SPORT SHOES — Step Into Your Game',
    },
    seo: {
      home: 'GSKY SPORT SHOES — Step Into Your Game',
      about: 'About Us — Gsky Sport Shoes',
      cart: 'Your Cart — Gsky Sport Shoes',
      checkout: 'Checkout — Gsky Sport Shoes',
      contact: 'Contact Us — Gsky Sport Shoes',
      login: 'Login — Gsky Sport Shoes',
      register: 'Create Account — Gsky Sport Shoes',
      shop: 'Shop Shoes — Gsky Sport Shoes',
      track: 'Track Your Order — Gsky Sport Shoes',
      wishlist: 'My Wishlist — Gsky Sport Shoes',
      orders: 'My Orders — Gsky Sport Shoes',
      profile: 'My Profile — Gsky Sport Shoes',
      notFound: 'Page Not Found — Gsky Sport Shoes',
      orderDetail: 'Order {{number}} — Gsky Sport Shoes',
      product: '{{name}} — Gsky Sport Shoes',
    },
  },
  sw: {
    nav: {
      home: 'Nyumbani', about: 'Kuhusu', testimonials: 'Maoni', services: 'Huduma Zetu',
      team: 'Timu Yetu', shop: 'Duka', arrivals: 'Vitu Vipya', track: 'Fuatilia Agizo', contact: 'Wasiliana',
    },
    common: {
      search: 'Tafuta viatu…', login: 'Ingia', signup: 'Jisajili', logout: 'Toka',
      dashboard: 'Dashibodi', cart: 'Rukoba', viewAll: 'Angalia zote →', shopNow: 'Numua Sasa',
      addToCart: 'Ongeza kwenye Rukoba', view: 'Angalia', outOfStock: 'Imeisha', noSizes: 'Hakuna ukubwa',
      remove: 'Ondoa', continueShopping: 'Endelea kununua', subtotal: 'Jumla Ndogo',
      deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla', yourCart: 'Rukoba Wako', size: 'Ukubwa',
      orders: 'Maagizo', profile: 'Profili', wishlist: 'Orodha ya Ninavyopenda',
    },
    status: {
      PENDING: 'Inasubiri', PROCESSING: 'Inachakatwa', SHIPPED: 'Imesafirishwa', DELIVERED: 'Imefikishwa',
      COMPLETED: 'Imekamilika', CANCELLED: 'Imesitishwa', PAID: 'Imelipwa', FAILED: 'Imeshindikana',
    },
    hero: {
      badge: 'Viatu vya Ubora. Bei Nzuri.',
      title: 'GSKY SPORT SHOES', subtitle: 'INGIA KATIKA MWENZAKO.',
      shopNow: 'NUMUA SASA →', whatsapp: 'WHATSAPP', hot: 'Moto sasa',
      styles: 'Mitindo', categories: 'Kategoria', quality: 'Ubora',
    },
    footer: {
      tagline: 'Viatu vya ubora kwa bei nzuri. Ingia katika mchezo wako na Gsky.',
      whatsapp: 'WhatsApp Sisi', shop: 'Duka', company: 'Kampuni', findUs: 'Tupate',
      allShoes: 'Viatu Vyote', featured: 'Mpangilio', newArrivals: 'Vitu Vipya', bestSellers: 'Vinauzika Sana',
      track: 'Fuatilia Agizo Lako', about: 'Kuhusu Sisi', contact: 'Wasiliana',
      rights: 'Haki zote zimehifadhiwa.', developedBy: 'Imeandaliwa na',
    },
    home: {
      shopByCategory: 'Nunua kwa Kategoria', products: 'bidhaa',
      newArrivals: 'Vitu Vipya', newArrivalsSub: 'Mtindo mpya — vitu vya hivi punde kwenye maduka yetu',
      featuredCollection: 'Mkusanyiko uliochaguliwa', featuredSub: 'Vipendwa vilivyochaguliwa kwa makini',
      bestSellers: 'Vinauzika Sana', bestSellersSub: 'Vinavyopendwa na wateja wetu',
    },
    shop: {
      title: 'VIATU VYOTE', productsAvailable: 'Bidhaa {{n}} zinapatikana',
      searchPh: 'Tafuta viatu…', allCategories: 'Kategoria Zote', allSizes: 'Ukubwa Wote',
      sortNewest: 'Mpya Kabisa', sortPriceAsc: 'Bei: Ya Chini Hadi Juu', sortPriceDesc: 'Bei: Ya Juu Hadi Chini',
      sortBestSellers: 'Vinauzika Sana', noShoesFound: 'Hakuna viatu vilivyopatikana',
      noShoesDesc: 'Jaribu utafutaji au kichujio kingine.', clearFilters: 'Futa vichujio',
      loadMore: 'Onyesha bidhaa zaidi',
    },
    product: {
      newArrival: 'Kipya', bestSeller: 'Kinauzika Sana', featured: 'Kilichochaguliwa',
      home: 'Nyumbani', shop: 'Duka', selectSize: 'Chagua Ukubwa',
      inStock: '{{n}} zipo', outOfStock: 'Ukubwa huu umeisha',
      sizeGuide: '📏 Mwongozo wa Ukubwa (EU)', us: 'US', uk: 'UK', footCm: 'Urefu wa mguu (cm)',
      sizeGuideHelp: 'Pima mguu wako kutoka kisigino hadi kidole kirefu, kisha linganisha urefu. Ukikuta kati ya ukubwa, chukua nusu kubwa zaidi. WhatsApp sisi kwa 0675029833 kwa usaidizi wa ukubwa.',
      quantity: 'Kiasi', addToCart: '🛒 ONGEZA KWENYE RUKOBA', buyNow: 'NUMUA SASA',
      whatsappProduct: 'WHATSAPP KUHUSU BIDHAA HII',
      customerReviews: 'Maoni ya Wateja ({{n}})',
      noReviews: 'Hakuna maoni bado. Kuwa wa kwanza kutoa maoni kuhusu bidhaa hii!',
      writeReview: 'Andika Maoni', rating: 'Alama', yourComment: 'Maoni yako',
      commentPh: 'Viatu viko vipi?', addPhoto: 'Ongeza picha (hiari)',
      photoAttached: 'Picha imeambatishwa', submitReview: 'Tuma Maoni',
      loginToReview: 'Ingia kuandika maoni kwa bidhaa ulizonunua.',
      customerPhoto: 'Picha ya mteja', pleaseSelectSize: 'Tafadhali chagua ukubwa',
      pleaseLoginCart: 'Tafadhali ingia ili kuongeza bidhaa kwenye rukoba', pleaseLoginCheckout: 'Tafadhali ingia kufanya malipo',
      addedToCart: 'Bidhaa imeongezwa kwenye rukoba ✓', thanksReview: 'Asante kwa maoni yako!',
      productNotFound: 'Bidhaa haikupatikana',
    },
    cart: {
      title: 'RUKOBA WAKO', emptyTitle: 'Rukoba lako halina bidhaa',
      emptyDesc: 'Tazama duka letu na ongeza viatu vipya.', remove: 'Ondoa',
      clearCart: 'Futa rukoba', orderSummary: 'Muhtasari wa Agizo', subtotal: 'Jumla Ndogo',
      deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla', checkout: 'Fanya Malipo →',
      continueShopping: 'Endelea kununua', size: 'Ukubwa',
      itemRemoved: 'Bidhaa imeondolewa kwenye rukoba',
    },
    checkout: {
      stepDelivery: 'Uwasilishaji', stepPayment: 'Malipo', stepDone: 'Imekamilika',
      emptyTitle: 'Rukoba lako halina bidhaa', emptyDesc: 'Ongeza viatu kwanza, kisha fanya malipo.',
      deliveryDetails: 'Maelezo ya Uwasilishaji', fullName: 'Jina kamili', phoneNumber: 'Namba ya simu',
      email: 'Barua pepe', city: 'Mji', deliveryLocation: 'Eneo la uwasilishaji',
      selectLocation: 'Chagua eneo lako', street: 'Mtaa / Mahali',
      streetPh: 'mf. DIT, jengo 4', deliveryNotes: 'Ujumbe wa uwasilishaji (hiari)',
      notesPh: 'Maelekezo yoyote ya uwasilishaji', continueToPayment: 'Endelea kwa Malipo →',
      orderSummary: 'Muhtasari wa Agizo', deliveryLabel: 'Uwasilishaji ({{zone}})',
      yourLocation: 'Mahali pako', discount: 'Punguzo ({{code}})', promoApplied: 'Promo {{code}} imetumika',
      remove: 'Ondoa', promoCode: 'Msimbo wa promo', apply: 'Tumia',
      minOrder: 'Agizo la chini kwa msimbo huu ni {{amount}}', promoAppliedMsg: 'Promo {{code}} imetumika!',
      choosePayment: 'Chagua Njia ya Malipo', orderLine: 'Agizo {{number}} · Jumla {{total}}',
      cardPayment: 'Malipo ya Kadi', cardNote: 'Kadi ya mkopo / kadi ya benki',
      processingPayment: 'Tunachakata malipo yako ya mtihani…', reference: 'Rejea: {{ref}}',
      simulated: 'Huu ni malipo ya kujaribu tu. Hakuna pesa halisi zinazotozwa.',
      pay: 'Lipa {{amount}}', paymentSuccess: 'Malipo Yamefanikiwa!',
      orderPaid: 'Agizo lako {{number}} limelipwa. Barua pepe ya uthibitisho inaelekea kwako.',
      totalPaid: 'Jumla iliyolipwa', payment: 'Malipo', weContact: 'Tutawasiliana nawe kwa {{phone}} kwa ajili ya uwasilishaji.',
      viewOrder: 'Angalia Agizo', continueShopping: 'Endelea Kununua',
      paymentFailed: 'Malipo yameshindikana. Tafadhali jaribu tena.', paymentProcessing: 'Malipo bado yanachakatwa. Angalia hali ya agizo lako baadaye.',
    },
    login: {
      title: 'Karibu tena 👟', subtitle: 'Ingia kwenye akaunti yako ya Gsky.',
      accountCreated: 'Akaunti imeundwa! Barua pepe ya kukaribisha imetumwa kwa {{email}}. Ingia hapa chini kuendelea.',
      email: 'Barua pepe', password: 'Nenosiri', login: 'Ingia',
      noAccount: 'Huna akaunti?', createOne: 'Unda moja',
      welcomeBack: 'Karibu tena, {{name}}!',
    },
    register: {
      title: 'Unda akaunti yako 👟', subtitle: 'Jiunge na familia ya Gsky VIP.',
      fullName: 'Jina kamili', namePh: 'Nia Joseph', email: 'Barua pepe', phoneNumber: 'Namba ya simu',
      password: 'Nenosiri', passPh: 'Angalau herufi 6', confirmPassword: 'Thibitisha nenosiri',
      repeatPh: 'Rudia nenosiri', create: 'Unda Akaunti', haveAccount: 'Tayari una akaunti?',
      login: 'Ingia', accountCreated: 'Akaunti imeundwa! Barua pepe imetumwa kwa {{email}}. Tafadhali ingia.',
    },
    profile: {
      title: 'PROFILI YANGU', memberSince: 'Mwanachama tangu {{date}}', fullName: 'Jina kamili',
      phoneNumber: 'Namba ya simu', emailCannotChange: 'Barua pepe (haiwezi kubadilishwa)',
      save: 'Hifadhi Mabadiliko', updated: 'Profili imesasishwa ✓',
    },
    orders: {
      title: 'MAAGIZO YANGU', noOrders: 'Bado hakuna maagizo',
      noOrdersDesc: 'Ukitoa agizo litaonekana hapa.', shopNow: 'Numua Sasa',
    },
    orderDetail: {
      myOrders: '← Maagizo yangu', placed: 'Uliwekwa {{date}}',
      notPaid: 'Agizo hili halijalipwa bado.', completePayment: 'Kamilisha malipo ili viatu vyako viweze kusafirishwa.',
      payNow: 'Lipa sasa (Sandbox)', processing: 'Tunachakata…',
      delivered: '🎉 Kifurushi chako kimefika!',
      youConfirmed: '✓ Umethibitisha uwasilishaji {{date}}. Tutaalika kukamilisha hivi karibuni.',
      received: 'Umepokea viatu? Thibitisha uwasilishaji ili kukamilisha agizo lako.',
      confirming: 'Tunathibitisha…', confirmDelivery: 'Thibitisha Uwasilishaji',
      items: 'Bidhaa', subtotal: 'Jumla Ndogo', deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla',
      delivery: 'Uwasilishaji', notes: 'Ujumbe: {{notes}}', payments: 'Malipo',
      paymentSuccess: 'Malipo yamefanikiwa!', deliveryConfirmed: 'Uwasilishaji umethibitishwa. Asante!',
      paymentProcessing: 'Malipo bado yanachakatwa. Jaribu tena baadaye.',
    },
    track: {
      title: 'Fuatilia Agizo Lako',
      subtitle: 'Weka barua pepe uliyotumia kwenye malipo na Namba ya Agizo kutoka barua pepe ya uthibitisho.',
      billingEmail: 'Barua pepe ya malipo', orderId: 'Namba ya Agizo', track: 'FUATILIA',
      placed: '{{name}} · Uliwekwa {{date}}', deliveryAddress: 'Anwani ya Uwasilishaji',
      items: 'Bidhaa', deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla', notes: 'Ujumbe: {{notes}}',
      sizeQty: '(Ukubwa {{size}} × {{qty}})',
    },
    timeline: {
      placed: 'Agizo Limewekwa', processing: 'Inachakatwa', assigned: 'Limekabidhiwa kwa Dereva',
      delivered: 'Limefikishwa', completed: 'Limekamilika', cancelled: 'Agizo hili limesitishwa',
      cancelledDesc: 'Wasiliana nasi kwa WhatsApp kwa usaidizi.',
      currentStage: '{{stage}} ndiyo hatua ya sasa. Inayofuata: {{next}}.',
      orderCompleted: '🎉 Agizo limekamilika. Furahia viatu vyako!',
      confirmedByClient: '✓ Uwasilishaji umethibitishwa na mteja {{date}}',
    },
    productCard: {
      new: 'Mpya', bestSeller: 'Kinauzika Sana', outOfStock: 'Imeisha',
      sizes: 'Ukubwa: {{sizes}}', noSizes: 'Hakuna ukubwa', addToCart: 'Ongeza kwenye Rukoba', view: 'Angalia',
      added: 'Bidhaa imeongezwa kwenye rukoba ✓', loginToAdd: 'Tafadhali ingia ili kuongeza bidhaa kwenye rukoba',
      outOfStockMsg: 'Bidhaa imeisha kwa sasa',
    },
    homeSections: {
      shopNow: 'Numua Sasa', chatWhatsapp: 'Ongea kwa WhatsApp',
    },
    services: {
      label: 'Huduma Zetu', title: 'HUDUMA UNAYOIAMINI',
      subtitle: 'Kutoka Dar es Salaam hadi kwingineko Tanzania — tunarahisisha ununuzi wa viatu vya michezo.',
      s1t: 'Uwasilishaji wa Haraka Dar es Salaam',
      s1d: 'Uwasilishaji wa siku hiyo hiyo Dar es Salaam na usafirishaji wa haraka nchini kote. Agiza kwa WhatsApp au mtandaoni na tutafikisha viatu vyako haraka.',
      s2t: 'Dhamana ya Ubora',
      s2d: 'Kila jozi hukaguliwa kabla ya kuondoka dukani kwetu DIT, Morogoro Road. Kama kuna tatizo, tunabadilisha au kurejesha fedha — bila maneno mengi.',
      s3t: 'Kuagiza kwa WhatsApp',
      s3d: 'Unapenda kuongea? Tutumie ujumbe WhatsApp, tuambie ukubwa wako na mfano, na sisi tutashughulikia yote. Malipo ya mkononi yanapatikana.',
      s4t: 'Kubadilishana Ukubwa',
      s4d: 'Ukubwa usiofaa? Hakuna shida. Badilisha jozi yoyote isiyotumika ndani ya siku chache baada ya kununua, au tutembelee Morogoro Road ujaribu kabla ya kununua.',
      shopNow: 'Numua Sasa', chatWhatsapp: 'Ongea kwa WhatsApp',
    },
    team: {
      label: 'Timu Yetu', title: 'WATU WALIO NYUMA YA GSKY',
      subtitle: 'Timu ndogo yenye shauku inayosaidia Tanzania kucheza kwa viatu sahihi.',
      m1r: 'Mwanzilishi na Meneja wa Mauzo',
      m1d: 'Alianzisha Gsky Sport Shoes DIT kwa lengo moja — buti za mpira bora kwa bei ya uaminifu.',
      m2r: 'Uendeshaji na Ghala',
      m2d: 'Anahakikisha kila agizo linakaguliwa, kufungwa na kutoka haraka kutoka kituo chetu cha Morogoro Road.',
      m3r: 'Huduma kwa Wateja',
      m3d: 'Njia yako ya kwanza ya mawasiliano kwa WhatsApp — majibu ya haraka, usaidizi wa ukubwa na taarifa za agizo.',
      cta: 'Unataka kufanya kazi nasi au kutembelea duka?', ctaLink: 'Tuma ujumbe kwa timu →',
    },
    testimonials: {
      label: 'Maoni', title: 'WATEJA WETU WANASEMA NINI',
      r1: 'Mchezaji wa mpira, Kinondoni',
      q1: 'Nilinunua Gsky Predator FG kwa ligi yangu ya Jumapili. Kushikia kwenye ardhi ngumu ni ajabu — nimefunga mara mbili kwenye mechi ya kwanza. Uwasilishaji Kinondoni ulikuwa siku hiyo hiyo!',
      r2: 'Mwanariadha wa kukimbia, Mikocheni',
      q2: 'Runner Pro ni kiatu kizuri zaidi nimewahi kuwa nacho. Kipapu, kinapumua na bei ni bora kuliko chapa kubwa. Gsky sasa ni duka langu la kwanza.',
      r3: 'Kocha, Chang’ombe',
      q3: 'Niliagiza jozi 12 za Matchday TF kwa wachezaji wa akademia yangu. Timu iliwasiliana kila kitu kwa WhatsApp na buti zilidumu msimu mzima.',
      r4: 'Mchezaji wa futsal, Buguruni',
      q4: 'Court Indoor ni kamili kwa ligi yetu ya futsal. Soli zisizoacha alama, kushikia vizuri, na wenzangu wanaendelea kuuliza nilizipata wapi!',
      r5: 'Mwenye gym, Posta',
      q5: 'Ninauza viatu vya Gsky Power Gym kwa wanachama wangu. Ubora mzuri, bei nzuri za jumla na kujazwa tena kwa uhakika. Ninapendekeza kufanya kazi nao.',
      r6: 'Mteja, Mwenge',
      q6: 'Kuagiza kwa WhatsApp ni rahisi, uwasilishaji wa haraka na walinisaidia kubadilisha ukubwa bila shida yoyote. Huduma bora kabisa.',
    },
    newsletter: {
      title: 'JIUNGE NA ORODHA YA GSKY VIP', sub: 'Pata vitu vipya, ofa maalum na taarifa za kipekee za Gsky.',
      name: 'Jina lako', email: 'Barua pepe', phone: 'Namba ya simu (hiari)',
      size: 'Ukubwa wako wa viatu (hiari)', agree: 'Nakubali kupokea barua pepe za matangazo kutoka Gsky Sport Shoes.',
      subscribe: 'Jiunge — Ingia kwenye Orodha ya VIP', needConsent: 'Tafadhali kubali kupokea barua pepe za matangazo',
      welcome: 'Karibu kwenye orodha ya Gsky VIP! 👟',
      unsubTitle: 'Jiondoe kwenye Orodha', unsubSub: 'Weka barua pepe yako ili usipokee tena barua pepe za matangazo.',
      unsubBtn: 'Jiondoe', unsubDone: 'Umejiondoa',
      unsubDoneSub: 'Hutapokea tena barua pepe za matangazo kutoka Gsky Sport Shoes.',
      unsubSeo: 'Jiondoe kwenye Orodha — Gsky Sport Shoes',
    },
    contact: {
      title: 'WASILIANA NASI', subtitle: 'Tunapenda kusikia kutoka kwako.',
      visitStore: 'Tembelea Duka Letu', storeLine: 'Gsky Sport Shoes · DIT, Morogoro Road · Dar es Salaam',
      address: 'Anwani', whatsapp: 'WhatsApp', hours: 'Saa za Kazi',
      hoursLine: 'Jumatatu – Jumamosi\n9:00 asubuhi – 7:00 jioni',
      sendMessage: 'Tutumie ujumbe', reply: 'Tunajibu kila ujumbe ndani ya siku moja ya kazi.',
      yourName: 'Jina lako', yourEmail: 'Barua pepe yako', subject: 'Mada',
      subjectPh: 'Swali la agizo, usaidizi wa ukubwa, ushirikiano…', message: 'Ujumbe', messagePh: 'Tunawezaje kusaidia?',
      send: 'Tuma Ujumbe', noteWhatsapp: 'Njia ya haraka zaidi kutufikia', noteEmail: 'Kwa maswali rasmi',
      noteInstagram: 'Fuata mtindo wetu wa hivi punde', noteTiktok: 'Nyuma ya pazia', noteFacebook: 'Taarifa za jamii',
    },
    about: {
      title: 'KUHUSU GSKY SPORT SHOES', subtitle: 'Ingia katika mchezo wako.',
      whoWeAre: 'Sisi ni nani',
      p1: 'Gsky Sport Shoes ni duka la viatu vya michezo na sneakers lililopo Dar es Salaam, DIT, Morogoro Road. Tunaamini mafanikio makubwa huanza kutoka chini — ndiyo maana tunauza viatu bora vya michezo kwa kukimbia, mpira wa kikapu, mpira wa miguu, mazoezi na matumizi ya kila siku kwa bei nzuri.',
      p2: 'Iwe unafuata rekodi yako binafsi, unatawala uwanja, au unataka tu jozi safi ya sneakers kwa mitaa — Gsky inakuhudumia. Vinjari duka letu mtandaoni, au wasiliana nasi kwa WhatsApp na tutakusaidia kupata ukubwa wako kamili.',
      standFor: 'Tunachosimamia',
      v1t: 'Ubora wa Kwanza', v1d: 'Kila jozi tunayouza imechaguliwa kwa kudumu, raha na utendaji.',
      v2t: 'Bei Nzuri', v2d: 'Thamani halisi ya pesa zako — viatu bora vya michezo bila bei za juu kupita kiasi.',
      v3t: 'Huduma Binafsi', v3d: 'Tutumie ujumbe WhatsApp wakati wowote. Tunakusaidia kuchagua ukubwa sahihi.',
      v4t: 'Uwasilishaji wa Haraka', v4d: 'Uwasilishaji wa haraka kote Dar es Salaam kwa ufungaji makini.',
      ready: 'Uko tayari kuingia katika mchezo wako?', shopNow: 'NUMUA SASA', whatsappUs: 'WhatsApp Sisi',
    },
    wishlist: {
      title: 'ORODHA YA NINAVYOPENDA', sub: 'Viatu ulivyohifadhi kwa baadaye.',
      emptyTitle: 'Orodha yako ya kupenda haina bidhaa', emptyDesc: 'Bonyeza moyo kwenye kiatu chochote kuihifadhi hapa.',
    },
    notFound: {
      title: 'Ukurasa haukupatikana', subtitle: 'Ukurasa unaoutafuta haupo.',
      backHome: 'Rudi Nyumbani',
    },
    error: {
      title: 'Kuna tatizo limetokea', retry: 'Jaribu Tena', home: 'Rudi Nyumbani',
      defaultSeo: 'GSKY SPORT SHOES — Ingia Katika Mchezo Wako',
    },
    seo: {
      home: 'GSKY SPORT SHOES — Ingia Katika Mchezo Wako',
      about: 'Kuhusu Sisi — Gsky Sport Shoes',
      cart: 'Rukoba Wako — Gsky Sport Shoes',
      checkout: 'Malipo — Gsky Sport Shoes',
      contact: 'Wasiliana Nasi — Gsky Sport Shoes',
      login: 'Ingia — Gsky Sport Shoes',
      register: 'Unda Akaunti — Gsky Sport Shoes',
      shop: 'Numua Viatu — Gsky Sport Shoes',
      track: 'Fuatilia Agizo Lako — Gsky Sport Shoes',
      wishlist: 'Orodha yangu — Gsky Sport Shoes',
      orders: 'Maagizo Yangu — Gsky Sport Shoes',
      profile: 'Profili Yangu — Gsky Sport Shoes',
      notFound: 'Ukurasa Haupatikani — Gsky Sport Shoes',
      orderDetail: 'Agizo {{number}} — Gsky Sport Shoes',
      product: '{{name}} — Gsky Sport Shoes',
    },
  },
};

export const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('gsky_lang') || 'en');
  useEffect(() => {
    localStorage.setItem('gsky_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = translations[lang] || translations.en;
  const toggle = () => setLang((l) => (l === 'en' ? 'sw' : 'en'));

  const tf = (template, vars = {}) =>
    template ? template.replace(/\{\{(\w+)\}\}/g, (m, k) => (k in vars ? String(vars[k]) : m)) : template;

  const statusLabel = (key) => (t.status && t.status[key] ? t.status[key] : key);

  return (
    <LanguageContext.Provider value={{ lang, t, tf, statusLabel, toggle, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
